import type { AuditAction } from "../audit-event/audit-event.js";

export const auditActionLabels: Record<AuditAction, string> = {
  "patient.merge": "Merge hồ sơ bệnh nhân",
  "patient.identifier-conflict": "Chặn trùng định danh bệnh nhân",
  "auth.login.success": "Đăng nhập thành công",
  "auth.login.failure": "Đăng nhập thất bại",
  "access.denied": "Truy cập bị từ chối",
  "patient.list": "Tải danh sách bệnh nhân",
  "patient.create": "Tạo bệnh nhân",
  "patient.read": "Đọc bệnh nhân",
  "patient.fhir-export": "Xuất Patient FHIR",
  "patient.fhir-bundle-export": "Xuất Bundle hồ sơ bệnh nhân",
  "patient.fhir-document-bundle-export": "Xuất document Bundle hồ sơ bệnh nhân",
  "provider-directory.read": "Đọc Provider Directory",
  "provider-directory.fhir-export": "Xuất Provider Directory FHIR",
  "record-transfer.list": "Tải gói chuyển hồ sơ",
  "record-transfer.create": "Tạo gói chuyển hồ sơ",
  "record-transfer.read": "Đọc gói chuyển hồ sơ",
  "record-transfer.send": "Gửi gói chuyển hồ sơ",
  "record-transfer.fail": "Ghi nhận lỗi chuyển hồ sơ",
  "record-transfer.retry": "Thử gửi lại gói chuyển hồ sơ",
  "record-transfer.dead-letter": "Đưa gói chuyển hồ sơ vào hàng lỗi cuối",
  "record-transfer.receive": "Xác nhận nhận gói chuyển hồ sơ",
  "record-transfer.acknowledgement-callback": "Callback xác nhận nhận gói chuyển hồ sơ",
  "record-transfer.fhir-export": "Xuất gói chuyển hồ sơ FHIR",
  "encounter.list": "Tải lượt khám",
  "encounter.create": "Tạo lượt khám",
  "encounter.read": "Đọc lượt khám",
  "encounter.finish": "Kết thúc lượt khám",
  "encounter.fhir-export": "Xuất Encounter FHIR",
  "allergy-intolerance.list": "Tải dị ứng/cảnh báo",
  "allergy-intolerance.create": "Ghi nhận dị ứng/cảnh báo",
  "allergy-intolerance.read": "Đọc dị ứng/cảnh báo",
  "allergy-intolerance.fhir-export": "Xuất AllergyIntolerance FHIR",
  "condition.list": "Tải chẩn đoán",
  "condition.create": "Ghi nhận chẩn đoán",
  "condition.read": "Đọc chẩn đoán",
  "condition.fhir-export": "Xuất Condition FHIR",
  "medication-request.list": "Tải chỉ định thuốc",
  "medication-request.create": "Tạo chỉ định thuốc",
  "medication-request.read": "Đọc chỉ định thuốc",
  "medication-request.fhir-export": "Xuất MedicationRequest FHIR",
  "medication-dispense.list": "Tải cấp phát thuốc",
  "medication-dispense.create": "Ghi nhận cấp phát thuốc",
  "medication-dispense.read": "Đọc cấp phát thuốc",
  "medication-dispense.fhir-export": "Xuất MedicationDispense FHIR",
  "medication-administration.list": "Tải dùng thuốc thực tế",
  "medication-administration.create": "Ghi nhận dùng thuốc thực tế",
  "medication-administration.read": "Đọc dùng thuốc thực tế",
  "medication-administration.fhir-export": "Xuất MedicationAdministration FHIR",
  "observation.list": "Tải chỉ số lâm sàng",
  "observation.create": "Ghi nhận chỉ số lâm sàng",
  "observation.read": "Đọc chỉ số lâm sàng",
  "observation.fhir-export": "Xuất Observation FHIR",
  "service-request.list": "Tải chỉ định dịch vụ",
  "service-request.create": "Tạo chỉ định dịch vụ",
  "service-request.read": "Đọc chỉ định dịch vụ",
  "service-request.fhir-export": "Xuất ServiceRequest FHIR",
  "workflow-task.list": "Tải công việc thực thi",
  "workflow-task.create": "Tạo công việc thực thi",
  "workflow-task.read": "Đọc công việc thực thi",
  "workflow-task.fhir-export": "Xuất Task FHIR",
  "procedure.list": "Tải thủ thuật/hoạt động",
  "procedure.create": "Ghi nhận thủ thuật/hoạt động",
  "procedure.read": "Đọc thủ thuật/hoạt động",
  "procedure.fhir-export": "Xuất Procedure FHIR",
  "diagnostic-report.list": "Tải báo cáo kết quả",
  "diagnostic-report.create": "Tạo báo cáo kết quả",
  "diagnostic-report.read": "Đọc báo cáo kết quả",
  "diagnostic-report.fhir-export": "Xuất DiagnosticReport FHIR",
  "imaging-study.list": "Tải nghiên cứu hình ảnh",
  "imaging-study.create": "Tạo nghiên cứu hình ảnh",
  "imaging-study.read": "Đọc nghiên cứu hình ảnh",
  "imaging-study.fhir-export": "Xuất ImagingStudy FHIR",
  "clinical-document.list": "Tải tài liệu bệnh án",
  "clinical-document.create": "Tạo tài liệu bệnh án",
  "clinical-document.sign": "Ký tài liệu bệnh án",
  "clinical-document.fhir-export": "Xuất DocumentReference FHIR",
  "clinical-document.provenance-export": "Xuất Provenance FHIR của tài liệu",
  "consent.list": "Tải đồng ý chia sẻ hồ sơ",
  "consent.create": "Tạo đồng ý chia sẻ hồ sơ",
  "consent.revoke": "Thu hồi đồng ý chia sẻ hồ sơ",
  "consent.fhir-export": "Xuất Consent FHIR",
  "audit-event.list": "Tải nhật ký kiểm toán",
  "audit-event.fhir-export": "Xuất AuditEvent FHIR",
  "audit-event.integrity-verify": "Kiểm tra toàn vẹn audit"
};
