export const selectRecordTransferSql = `SELECT
  id,
  patient_id,
  status,
  priority,
  bundle_type,
  bundle_id,
  source_organization_id,
  recipient_organization_id,
  consent_reference,
  requested_by_actor_id,
  reason,
  requested_at,
  sent_at,
  received_at,
  received_by_actor_id,
  acknowledgement_reference,
  failed_at,
  failure_reason,
  next_retry_at,
  retry_count,
  dead_lettered_at,
  note,
  created_at,
  updated_at
  FROM record_transfers`;

export const upsertRecordTransferSql = `INSERT INTO record_transfers (
  id,
  patient_id,
  status,
  priority,
  bundle_type,
  bundle_id,
  source_organization_id,
  recipient_organization_id,
  consent_reference,
  requested_by_actor_id,
  reason,
  requested_at,
  sent_at,
  received_at,
  received_by_actor_id,
  acknowledgement_reference,
  failed_at,
  failure_reason,
  next_retry_at,
  retry_count,
  dead_lettered_at,
  note,
  created_at,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24)
ON CONFLICT (id) DO UPDATE SET
  patient_id = EXCLUDED.patient_id,
  status = EXCLUDED.status,
  priority = EXCLUDED.priority,
  bundle_type = EXCLUDED.bundle_type,
  bundle_id = EXCLUDED.bundle_id,
  source_organization_id = EXCLUDED.source_organization_id,
  recipient_organization_id = EXCLUDED.recipient_organization_id,
  consent_reference = EXCLUDED.consent_reference,
  requested_by_actor_id = EXCLUDED.requested_by_actor_id,
  reason = EXCLUDED.reason,
  requested_at = EXCLUDED.requested_at,
  sent_at = EXCLUDED.sent_at,
  received_at = EXCLUDED.received_at,
  received_by_actor_id = EXCLUDED.received_by_actor_id,
  acknowledgement_reference = EXCLUDED.acknowledgement_reference,
  failed_at = EXCLUDED.failed_at,
  failure_reason = EXCLUDED.failure_reason,
  next_retry_at = EXCLUDED.next_retry_at,
  retry_count = EXCLUDED.retry_count,
  dead_lettered_at = EXCLUDED.dead_lettered_at,
  note = EXCLUDED.note,
  updated_at = EXCLUDED.updated_at`;
