export const selectProcedureSql = `SELECT
  id,
  patient_id,
  encounter_id,
  based_on_service_request_id,
  part_of_procedure_id,
  status,
  status_reason,
  category,
  code,
  performed_period,
  recorder_practitioner_id,
  asserter_practitioner_id,
  performers,
  reason_condition_id,
  body_site,
  outcome,
  report_references,
  note,
  created_at,
  updated_at
  FROM procedures`;

export const upsertProcedureSql = `INSERT INTO procedures (
  id,
  patient_id,
  encounter_id,
  based_on_service_request_id,
  part_of_procedure_id,
  status,
  status_reason,
  category,
  code,
  performed_period,
  recorder_practitioner_id,
  asserter_practitioner_id,
  performers,
  reason_condition_id,
  body_site,
  outcome,
  report_references,
  note,
  created_at,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7::jsonb, $8, $9::jsonb, $10::jsonb, $11, $12, $13::jsonb, $14, $15::jsonb, $16::jsonb, $17::jsonb, $18, $19, $20)
ON CONFLICT (id) DO UPDATE SET
  patient_id = EXCLUDED.patient_id,
  encounter_id = EXCLUDED.encounter_id,
  based_on_service_request_id = EXCLUDED.based_on_service_request_id,
  part_of_procedure_id = EXCLUDED.part_of_procedure_id,
  status = EXCLUDED.status,
  status_reason = EXCLUDED.status_reason,
  category = EXCLUDED.category,
  code = EXCLUDED.code,
  performed_period = EXCLUDED.performed_period,
  recorder_practitioner_id = EXCLUDED.recorder_practitioner_id,
  asserter_practitioner_id = EXCLUDED.asserter_practitioner_id,
  performers = EXCLUDED.performers,
  reason_condition_id = EXCLUDED.reason_condition_id,
  body_site = EXCLUDED.body_site,
  outcome = EXCLUDED.outcome,
  report_references = EXCLUDED.report_references,
  note = EXCLUDED.note,
  updated_at = EXCLUDED.updated_at`;
