export const selectMedicationDispenseSql = `SELECT
  id,
  patient_id,
  encounter_id,
  medication_request_id,
  status,
  status_reason,
  category,
  medication_code,
  quantity,
  days_supply,
  when_prepared,
  when_handed_over,
  dispenser_practitioner_id,
  destination_location_id,
  receiver_practitioner_id,
  dosage_instruction,
  note,
  created_at,
  updated_at
  FROM medication_dispenses`;

export const upsertMedicationDispenseSql = `INSERT INTO medication_dispenses (
  id,
  patient_id,
  encounter_id,
  medication_request_id,
  status,
  status_reason,
  category,
  medication_code,
  quantity,
  days_supply,
  when_prepared,
  when_handed_over,
  dispenser_practitioner_id,
  destination_location_id,
  receiver_practitioner_id,
  dosage_instruction,
  note,
  created_at,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7, $8::jsonb, $9::jsonb, $10::jsonb, $11, $12, $13, $14, $15, $16::jsonb, $17, $18, $19)
ON CONFLICT (id) DO UPDATE SET
  patient_id = EXCLUDED.patient_id,
  encounter_id = EXCLUDED.encounter_id,
  medication_request_id = EXCLUDED.medication_request_id,
  status = EXCLUDED.status,
  status_reason = EXCLUDED.status_reason,
  category = EXCLUDED.category,
  medication_code = EXCLUDED.medication_code,
  quantity = EXCLUDED.quantity,
  days_supply = EXCLUDED.days_supply,
  when_prepared = EXCLUDED.when_prepared,
  when_handed_over = EXCLUDED.when_handed_over,
  dispenser_practitioner_id = EXCLUDED.dispenser_practitioner_id,
  destination_location_id = EXCLUDED.destination_location_id,
  receiver_practitioner_id = EXCLUDED.receiver_practitioner_id,
  dosage_instruction = EXCLUDED.dosage_instruction,
  note = EXCLUDED.note,
  updated_at = EXCLUDED.updated_at`;
