export const selectImagingStudySql = `SELECT
  id,
  patient_id,
  encounter_id,
  based_on_service_request_id,
  diagnostic_report_id,
  status,
  study_instance_uid,
  accession_number,
  description,
  started_at,
  referrer_practitioner_id,
  interpreter_practitioner_id,
  endpoint_id,
  number_of_series,
  number_of_instances,
  series,
  created_at,
  updated_at
  FROM imaging_studies`;

export const upsertImagingStudySql = `INSERT INTO imaging_studies (
  id,
  patient_id,
  encounter_id,
  based_on_service_request_id,
  diagnostic_report_id,
  status,
  study_instance_uid,
  accession_number,
  description,
  started_at,
  referrer_practitioner_id,
  interpreter_practitioner_id,
  endpoint_id,
  number_of_series,
  number_of_instances,
  series,
  created_at,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16::jsonb, $17, $18)
ON CONFLICT (id) DO UPDATE SET
  patient_id = EXCLUDED.patient_id,
  encounter_id = EXCLUDED.encounter_id,
  based_on_service_request_id = EXCLUDED.based_on_service_request_id,
  diagnostic_report_id = EXCLUDED.diagnostic_report_id,
  status = EXCLUDED.status,
  study_instance_uid = EXCLUDED.study_instance_uid,
  accession_number = EXCLUDED.accession_number,
  description = EXCLUDED.description,
  started_at = EXCLUDED.started_at,
  referrer_practitioner_id = EXCLUDED.referrer_practitioner_id,
  interpreter_practitioner_id = EXCLUDED.interpreter_practitioner_id,
  endpoint_id = EXCLUDED.endpoint_id,
  number_of_series = EXCLUDED.number_of_series,
  number_of_instances = EXCLUDED.number_of_instances,
  series = EXCLUDED.series,
  updated_at = EXCLUDED.updated_at`;
