export const selectWorkflowTaskSql = `SELECT
  id,
  patient_id,
  encounter_id,
  based_on_service_request_id,
  status,
  intent,
  priority,
  code,
  description,
  business_status,
  requester_practitioner_id,
  owner_organization_id,
  owner_practitioner_id,
  authored_on,
  last_modified,
  execution_period,
  input_references,
  output_references,
  note,
  created_at,
  updated_at
  FROM workflow_tasks`;

export const upsertWorkflowTaskSql = `INSERT INTO workflow_tasks (
  id,
  patient_id,
  encounter_id,
  based_on_service_request_id,
  status,
  intent,
  priority,
  code,
  description,
  business_status,
  requester_practitioner_id,
  owner_organization_id,
  owner_practitioner_id,
  authored_on,
  last_modified,
  execution_period,
  input_references,
  output_references,
  note,
  created_at,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8::jsonb, $9, $10::jsonb, $11, $12, $13, $14, $15, $16::jsonb, $17::jsonb, $18::jsonb, $19, $20, $21)
ON CONFLICT (id) DO UPDATE SET
  patient_id = EXCLUDED.patient_id,
  encounter_id = EXCLUDED.encounter_id,
  based_on_service_request_id = EXCLUDED.based_on_service_request_id,
  status = EXCLUDED.status,
  intent = EXCLUDED.intent,
  priority = EXCLUDED.priority,
  code = EXCLUDED.code,
  description = EXCLUDED.description,
  business_status = EXCLUDED.business_status,
  requester_practitioner_id = EXCLUDED.requester_practitioner_id,
  owner_organization_id = EXCLUDED.owner_organization_id,
  owner_practitioner_id = EXCLUDED.owner_practitioner_id,
  authored_on = EXCLUDED.authored_on,
  last_modified = EXCLUDED.last_modified,
  execution_period = EXCLUDED.execution_period,
  input_references = EXCLUDED.input_references,
  output_references = EXCLUDED.output_references,
  note = EXCLUDED.note,
  updated_at = EXCLUDED.updated_at`;
